version: "3"
services: 
    caddy: 
        image: caddy:2.7
        restart: unless-stopped
        cap_add: 
            - NET_ADMIN
        ports: 
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes: 
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./caddy/data:/data
            - ./caddy/config:/config

    database: 
        image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
        ports: 
            - 5432:5432
        volumes: 
            - ./database/data:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: "directus"
            POSTGRES_PASSWORD_FILE: 'run/secrets/database_password'
            POSTGRES_DB: "directus"
        secrets: 
            - database_password

    cache: 
        image: redis:6

    directus: 
        build: ./directus
        ports: 
            - 8055:8055
        volumes: 
            - ./directus/uploads:/directus/uploads
        depends_on: 
            - cache
            - database
        environment: 
            KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
            SECRET_FILE: '/run/secrets/directus_secret'
            LOG_LEVEL: 'error'
            DB_CLIENT: "pg"
            DB_HOST: "database"
            DB_PORT: "5432"
            DB_DATABASE: "directus"
            DB_USER: "directus"
            DB_PASSWORD_FILE: '/run/secrets/database_password'

            CACHE_ENABLED: "true"
            CACHE_STORE: "redis"
            REDIS: "redis://cache:6379"

            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD_FILE: '/run/secrets/directus_admin_password'
        secrets: 
            - database_password
            - directus_secret
            - directus_admin_password
secrets: 
    database_password: 
        file: ./secrets/database_password.txt
    directus_secret: 
        file: ./secrets/directus_secret.txt
    directus_admin_password: 
        file: ./secrets/directus_admin_password.txt

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"